### ISSUE TITLE
Empty API response

### ISSUE THREAD

**Issue by MihaelN** [TwilioDevEd/authy2fa-laravel#14]
I get empty API response after creating user and entering login details. 

VM707:1 Uncaught SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Object.success (sessions.js:11)
    at j (jquery.js:3094)
    at Object.fireWith [as resolveWith] (jquery.js:3206)
    at x (jquery.js:8259)
    at XMLHttpRequest.<anonymous> (jquery.js:8600)

When I console.log API response, data is empty. 
sessions.js line 11 is ' var data = JSON.parse(data.replace(/1/g, "")); ', it cant parse empty value from API request.

**Comment by dprothero** [comment]
So sorry for not seeing this sooner. Do you see the request for `/auth/login` in the Network tab of your browser's developer tools? See if it's returing an error code, and if there's any content along with it that might explain the issue.
