### ISSUE TITLE
Different .env model than the tutorial 

### ISSUE THREAD

**Issue by GregBaugues** [TwilioDevEd/authy2fa-laravel#8]
The repo and README use .env.example and this format: 

```
APP_ENV=local
APP_DEBUG=true
APP_KEY=

DB_HOST=localhost
DB_DATABASE=authy2fa_laravel
DB_USERNAME=
DB_PASSWORD=

AUTHY_API_KEY=
```

The tutorial has: 

```
<?php

return array(

    'APP_DEBUG' => true,
    'AUTHY_TOKEN' => getenv('AUTHY_TOKEN') || 'your authy key here',

);
```

**Comment by GregBaugues** [comment]
Looks like the latter is pulling from `.env`, but the tutorial says: 

> Once we have an Authy API key, we store it in this .env file. (.env.local.php is displayed, but doesn't exist in the repo)
> 
> Now that we've configured our **Rails app**, let's take a look at how we register a user with Authy.

**Comment by mcelicalderon** [comment]
@GregBaugues gh-pages branch was out of sync with master. I fixed this and replaced Rails mistake. Thanks for the feedback!
